#**Assignment 2: QSAR Data Curation Using ChEMBL**

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [1]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 3.1 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 3.0 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 4.0 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [2]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Step 1: Search for Traget Protein

## **Target Identification (BRCA1)**
Search ChEMBL for the KRAS target and select the most relevant entry.

In [3]:
target = new_client.target
target_query = target.search("BRCA1")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Breast cancer type 1 susceptibility protein,19.0,False,CHEMBL5990,"[{'accession': 'P38398', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Lys-63-specific deubiquitinase BRCC36,19.0,False,CHEMBL4105965,"[{'accession': 'P46736', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Homo sapiens,BRCA1-associated protein,18.0,False,CHEMBL5291566,"[{'accession': 'Q7Z569', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Ubiquitin carboxyl-terminal hydrolase BAP1,15.0,False,CHEMBL1293314,"[{'accession': 'Q92560', 'component_descriptio...",SINGLE PROTEIN,9606

**Reterive Bioactivity data for selected target**

In [4]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL5990'

**Now retrieve only bioactivity data for target; **BRCA1(CHEMBL5990)** with reported IC 50  values in nM (nanomolar) unit.**

In [5]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [6]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6222842,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,4.6
1,None,None,6222843,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
2,None,None,6222844,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,52.8
3,None,None,6222845,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
4,None,None,6222846,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,15.0

In [7]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

# **Step 2: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected BRCA1 target.**

**Inspect Missing Values**

In [8]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [9]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6222842,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,4.6
1,None,None,6222843,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
2,None,None,6222844,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,52.8
3,None,None,6222845,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
4,None,None,6222846,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,15.0

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [10]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [11]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [12]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [13]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL1784774,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O...,4600.0,intermediate
1,CHEMBL1784771,CC(=O)N[C@@H](CCC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[...,250000.0,inactive
2,CHEMBL1784772,CC(=O)N[C@@H](CC(C(=O)O)C(=O)O)C(=O)N1CCC[C@H]...,52800.0,inactive
3,CHEMBL1784773,CC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)...,250000.0,inactive
4,CHEMBL1784704,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N[C@@H](C)C(=O)...,15000.0,inactive

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [14]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL1784774,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O...,4600.0,intermediate
1,CHEMBL1784771,CC(=O)N[C@@H](CCC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[...,250000.0,inactive
2,CHEMBL1784772,CC(=O)N[C@@H](CC(C(=O)O)C(=O)O)C(=O)N1CCC[C@H]...,52800.0,inactive
3,CHEMBL1784773,CC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)...,250000.0,inactive
4,CHEMBL1784704,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N[C@@H](C)C(=O)...,15000.0,inactive